### ISSUE TITLE
启动时出错：build modulesCaught exception: Error: invalid argument

### ISSUE THREAD

**Issue by Acvrock** [ShanghaitechGeekPie/fresh#1]
➜  fresh git:(master) ✗ npm -v
3.10.3
➜  fresh git:(master) ✗ node -v
v6.3.1
➜  fresh git:(master) ✗ npm start

> shanghaitech-fresh@2016.1.5 start /Users/moon/GitHub/fresh
> dora -p 8001 --plugins "webpack,hmr,proxy,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html"

          proxy: load rule from proxy.config.js
(node:7594) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
     livereload: listening on 35729
📦  553/553 build modulesCaught exception: Error: invalid argument
    at pathToArray (/Users/moon/GitHub/fresh/node_modules/dora-plugin-webpack/node_modules/koa-webpack-dev-middleware/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (/Users/moon/GitHub/fresh/node_modules/dora-plugin-webpack/node_modules/koa-webpack-dev-middleware/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/moon/GitHub/fresh/node_modules/dora-plugin-webpack/node_modules/koa-webpack-dev-middleware/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (/Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/lib/Compiler.js:229:25)
    at Compiler.next `(/Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)`
    at Compiler.<anonymous> (/Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/lib/ProgressPlugin.js:74:4)
    at Compiler.applyPluginsAsync (/Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/lib/Compiler.js:54:18)
    at /Users/moon/GitHub/fresh/node_modules/atool-build/node_modules/webpack/lib/Compiler.js:403:12
AnyProxy is about to exit with code: 0
➜  fresh git:(master) ✗

**Comment by eastpiger** [comment]
执行过npm install了没

**Comment by Acvrock** [comment]
早先 npm install 的时候是另外一个问题。。。
```
➜  fresh git:(master) ✗ npm install   
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/moon/.nvm/versions/node/v6.3.1/bin/node" "/Users/moon/.nvm/versions/node/v6.3.1/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: a_test@1.0.5
npm ERR! Valid install targets:
npm ERR! 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/moon/GitHub/fresh/npm-debug.log
➜  fresh git:(master) ✗ 

```

**Comment by eastpiger** [comment]
Update your npm...

**Comment by RunningCool** [comment]
thx
